library:
  source-dirs: src
tests:
  sudoku-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sudoku
copyright: 2020 Author name here
maintainer: example@example.com
dependencies:
  - lens
  - base >= 4.7 && < 5
name: sudoku
version: 0.1.0.0
extra-source-files:
  - README.md
  - ChangeLog.md
author: Author name here
github: githubuser/sudoku
license: BSD3
executables:
  sudoku-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sudoku
description: Please see the README on GitHub at <https://github.com/githubuser/sudoku#readme>
